KOBOT-13/CLIVING-BACK

- cliving/cliving/settings.py
- cliving/cliving/urls.py
- cliving/page/models.py
- cliving/page/serializers.py
- cliving/page/views.py
> 이미지 파일 api구현

- cliving/pose_model.py
pose_model 패키지화
Resolves : #12
> Feat: pose detect model 앱으로 만들기

- cliving/page/admin.py
- cliving/page/hold_utils.py
- cliving/page/models.py
- cliving/page/serializers.py
- cliving/page/urls.py
- cliving/page/views.py
> feat: 홀드 인식 모델 추가

- README.md
- cliving/page/serializers.py
- cliving/page/urls.py
- cliving/page/views.py
> 통계 페이지 api 완성

- cliving/cliving/urls.py
- cliving/page/hold_utils.py
- cliving/page/models.py
- cliving/page/serializers.py
- cliving/page/urls.py
- cliving/page/views.py
- cliving/requirements.txt
> 16 feat 홀드인식 기능 구현

- cliving/page/admin.py
- cliving/page/models.py
- cliving/page/serializers.py
- cliving/page/urls.py
- cliving/page/views.py
redoc오류로 인해
욜로 관련 모델 및 뷰셋을 잠시 주석처리 했음.
> 모든 api에 시리얼라이저 추가

- cliving/page/models.py
- cliving/page/urls.py
- cliving/page/views.py
> 이번달의 모든 page 반환 api 구현 완료

- cliving/page/serializers.py
- cliving/page/views.py
> hhmm 출력으로 전환 구현

- cliving/page/urls.py
- cliving/page/views.py
> Yolov8ViewSet 삭제

- cliving/page/serializers.py
- cliving/page/urls.py
- cliving/page/views.py
> page_id로 썸네일과 클립파일 검색하도록 구현

- cliving/page/hold_utils.py
- cliving/page/models.py
- cliving/page/serializers.py
- cliving/page/urls.py
- cliving/page/views.py
> 이미지 업로드 url 구현

- cliving/page/video_utils.py
- cliving/page/views.py
> mid time 계산 수정

- cliving/page/models.py
- cliving/page/pose_detect_utils.py
- cliving/page/urls.py
- cliving/page/views.py
> 35 feat pose detect 기능추가

- cliving/page/pose_detect_utils.py
> logic update

- cliving/page/pose_detect_utils.py
> 프레임 건너뛰는 로직

- cliving/page/pose_detect_utils.py
> fail_point_update

- cliving/cliving/settings.py
- cliving/page/models.py
- cliving/page/serializers.py
- cliving/page/views.py
> model save시 key값 중복 버그 해결

- cliving/page/models.py
- cliving/page/views.py
> color 추가 기능 구현 완료

- cliving/page/models.py
- cliving/page/views.py
> 색깔별 클립 개수 카운팅 리스트 구현

- cliving/page/views.py
이제 통계 페이지의 색깔별 try 횟수는 색깔당 clip이 만들어진 갯수를 바탕으로 측정됩니다.
> 66 feat 통계 수정

- cliving/page/models.py
> verbose_name수정

- cliving/cliving/settings.py
- cliving/users/admin.py
- cliving/users/models.py
- cliving/users/serializers.py
- cliving/users/urls.py
- cliving/users/views.py
feat: user 모델 및 로그인, 회원가입 등 기본 기능 구현 완료
> feat: user 모델 및 로그인, 회원가입 등 기본 기능 구현 완료

- cliving/cliving/settings.py
- cliving/users/urls.py
- cliving/users/views.py
> feat: 마이페이지 api

- cliving/users/admin.py
- cliving/users/serializers.py
- cliving/users/views.py
> feat: birth_date 제거

- cliving/users/admin.py
- cliving/users/models.py
- cliving/users/serializers.py
- cliving/users/urls.py
- cliving/users/views.py
인증번호 방식을 세션 방식에서, 인증모델을 이용한 방식으로 변경하였습니다.
PhoneVerification 모델에서 전화번호의 인증 여부를 관리합니다
> feat: 인증번호 방식 변경

- cliving/page/models.py
- cliving/page/urls.py
- cliving/page/views.py
- cliving/users/admin.py
- cliving/users/serializers.py
- cliving/users/urls.py
- cliving/users/views.py
Feat: ADD profile image update function
+) 어드민 페이지에서 nickname 확인 및 수정 가능하도록 수정
> Feat: ADD profile image update function

- cliving/page/pose_detect_utils.py
top_hold 좌표 처리를 중복되지 않도록 수정했습니다. 
pose_detect 에서 좌표값을 가져오지 못했을 때 기본값 할당이 아닌 NONE 값으로 처리되도록 수정했습니다.
> 74 skip frame 로직 수정

- cliving/cliving/settings.py
- cliving/page/admin.py
- cliving/page/models.py
- cliving/page/pose_detect_utils.py
- cliving/page/serializers.py
- cliving/page/views.py
- cliving/users/serializers.py
- cliving/users/urls.py
- cliving/users/views.py
89 feat user모델 추가를 위해 모든 모델 재구성
> 89 feat user모델 추가를 위해 모든 모델 재구성
